original_rom = "roms/jw_original.gb"
output_dir = "out"
emulator = "../bgb/bgb64"
patched_rom = "roms/jw_patched.gb"
patch_version = "0.2.1"

[script]
table = "tbl/jw-py.tbl"

[signs]
table = "tbl/jw-py.tbl"
output = "test_output_signs.yaml"
offset_start = 0x31E73
offset_end = 0x31EA0

